### ISSUE TITLE
FurnitureLib errors LightAPI

### ISSUE THREAD

**Issue by Fargus5** [BalrogGames/herosfaith#10]
`[21:32:33] [Server thread/INFO]: [FurnitureLib] Enabling FurnitureLib v1.9.2.9-DEV
[21:32:33] [Server thread/INFO]: ==========================================
[21:32:33] [Server thread/INFO]: FurnitureLibary Version: 1.9.2.9-DEV
[21:32:33] [Server thread/INFO]: Furniture Autor: Ste3et_C0st
[21:32:33] [Server thread/INFO]: Furniture Website: http://dicecraft.de
[21:32:33] [Server thread/INFO]: Furniture start load
[21:32:33] [Server thread/INFO]: Furniture find ProtectionLib: true
[21:32:33] [Server thread/WARN]: java.lang.NullPointerException
[21:32:33] [Server thread/WARN]: 	at ru.beykerykt.lightapi.LightAPI.deleteLight(LightAPI.java:235)
[21:32:33] [Server thread/WARN]: 	at ru.beykerykt.lightapi.LightAPI.deleteLight(LightAPI.java:217)
[21:32:33] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.main.LightManager.removeLight(LightManager.java:40)
[21:32:33] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.main.entity.fEntity.setFire(fEntity.java:306)
[21:32:33] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.Database.DeSerializer.loadDefMetadata(DeSerializer.java:146)
[21:32:33] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.Database.DeSerializer.loadArmorStandMetadata(DeSerializer.java:120)
[21:32:33] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.Database.DeSerializer.Deserialze(DeSerializer.java:78)
[21:32:33] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.Database.Database.loadAll(Database.java:78)
[21:32:33] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.Database.SQLManager.loadALL(SQLManager.java:54)
[21:32:33] [Server thread/WARN]: 	at de.Ste3et_C0st.FurnitureLib.main.FurnitureLib.onEnable(FurnitureLib.java:203)
[21:32:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[21:32:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[21:32:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[21:32:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
[21:32:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
[21:32:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
[21:32:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
[21:32:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
[21:32:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[21:32:33] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
[21:32:33] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)`

**Comment by Ste3et** [comment]
Die you Use this lightapi https://www.spigotmc.org/resources/lightapi-temporary-fork-3-2-4-1-12.48247/ ?

**Comment by Fargus5** [comment]
Problem has been fixed
Thanks @Ste3et
