### ISSUE TITLE
Cartographer crash

### ISSUE THREAD

**Issue by Fargus5** [BalrogGames/herosfaith#11]
`[18:56:04] [Server thread/INFO]: Fargus5 issued server command: /setmapcenter falteon
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Loading map falteon
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Loading config...
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Loading the presets...
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Loading the map settings...
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Loading all colors...
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Loaded the colors of preset '1.11.2.yml' successfully!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Loading all transparent blocks...
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Loaded the transparent blocks of preset '1.11.2.yml' successfully!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Loading map data...
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] An overlay was not found!!
[18:56:04] [Server thread/WARN]: [Cartographer] Map data not found! Reloading the map!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Loading the modules...
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] The 'radar' module has been loaded!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] The 'kingdoms' module has been loaded!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] The 'quests' module has been loaded!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] The 'display' module has been loaded!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] The 'waypoints' module has been loaded!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] The 'worldguard' module has been loaded!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] The 'citizens' module has been loaded!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Done loading the config!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Config loaded successfully!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Starting map renderer...
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Done loading map falteon
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Loaded the colors of preset '1.11.2.yml' successfully!
[18:56:04] [Server thread/INFO]: [Cartographer] [falteon] Loaded the transparent blocks of preset '1.11.2.yml' successfully!
[18:56:04] [Server thread/WARN]: Failed to handle packet for /83.112.152.221:55611
net.minecraft.server.v1_12_R1.ReportedException: Ticking player
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:385) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:138) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_12_R1.map.CraftMapCanvas.drawText(CraftMapCanvas.java:100) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at io.github.bananapuncher714.cartographer.map.CustomRenderer.render(CustomRenderer.java:242) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.map.CraftMapView.render(CraftMapView.java:146) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:333) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.WorldMap.a(WorldMap.java:288) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.ItemWorldMap.a(ItemWorldMap.java:305) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:310) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	... 8 more
[18:56:04] [Server thread/INFO]: Fargus5 lost connection: Internal server error
[18:56:04] [Server thread/INFO]: Fargus5 has quit!
[18:56:04] [Server thread/INFO]: [DiscordSRV] Player Fargus5 quit with silent quitting permission, not sending a quit message
[18:56:04] [Server thread/WARN]: [Quests] Quester data for UUID "22802907-e1f0-43f1-9d70-42fd63f831fc" not stored. Attempting manual data retrieval...
[18:56:04] [Server thread/INFO]: [Quests] Manual data retrieval succeeded for UUID "22802907-e1f0-43f1-9d70-42fd63f831fc"
[18:56:04] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Ticking player
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:385) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:398) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1095) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:319) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:174) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_12_R1.map.CraftMapCanvas.drawText(CraftMapCanvas.java:100) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at io.github.bananapuncher714.cartographer.map.CustomRenderer.render(CustomRenderer.java:242) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.map.CraftMapView.render(CraftMapView.java:146) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:333) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.WorldMap.a(WorldMap.java:288) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.ItemWorldMap.a(ItemWorldMap.java:305) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:310) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	... 9 more
[18:56:04] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_12_R1.map.CraftMapCanvas.drawText(CraftMapCanvas.java:100) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at io.github.bananapuncher714.cartographer.map.CustomRenderer.render(CustomRenderer.java:242) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.map.CraftMapView.render(CraftMapView.java:146) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:333) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.WorldMap.a(WorldMap.java:288) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.ItemWorldMap.a(ItemWorldMap.java:305) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:310) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:398) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1095) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:319) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:174) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

**Comment by Fargus5** [comment]
[19:00:16] [Server thread/INFO]: Fargus5 issued server command: /give Fargus5 map 1
[19:00:26] [Server thread/WARN]: Failed to handle packet for /83.112.152.221:55709
net.minecraft.server.v1_12_R1.ReportedException: Ticking player
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:385) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:138) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_12_R1.map.CraftMapCanvas.drawText(CraftMapCanvas.java:100) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at io.github.bananapuncher714.cartographer.map.CustomRenderer.render(CustomRenderer.java:242) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.map.CraftMapView.render(CraftMapView.java:146) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:333) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.WorldMap.a(WorldMap.java:288) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.ItemWorldMap.a(ItemWorldMap.java:305) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:310) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	... 8 more
[19:00:26] [Server thread/INFO]: Fargus5 lost connection: Internal server error
[19:00:26] [Server thread/INFO]: Fargus5 has quit!
[19:00:26] [Server thread/INFO]: [DiscordSRV] Player Fargus5 quit with silent quitting permission, not sending a quit message
[19:00:26] [Server thread/WARN]: [Quests] Quester data for UUID "22802907-e1f0-43f1-9d70-42fd63f831fc" not stored. Attempting manual data retrieval...
[19:00:26] [Server thread/INFO]: [Quests] Manual data retrieval succeeded for UUID "22802907-e1f0-43f1-9d70-42fd63f831fc"
[19:00:26] [Thread-61/INFO]: [Bank] Saving Bank for 22802907-e1f0-43f1-9d70-42fd63f831fc to file
[19:00:26] [Thread-61/INFO]: [Bank] Saved Bank for 22802907-e1f0-43f1-9d70-42fd63f831fc to file
