### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to RPGInventory v2.1.4 + RPGPlayerLeveling v3.6.3 + DisguiseAbilities v2.9.9 + ItemHoloEvent to ItemDrop vMysthoria

### ISSUE THREAD

**Issue by Fargus5** [BalrogGames/herosfaith#12]
Please to find here [latest.log](https://github.com/BalrogGames/herosfaith/files/1586106/latest.log) the latestlog with errors.

For Praya ItemDrop: See after line 9927

For Baksovic each line starting from line 43

For XeRicker each line starting from the first line

For OsipXD from line 166

This server is running CraftBukkit version git-Spigot-8cbfc85-202da97 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

These errors appears when 2 npc created with mythicmobs and citizens fight each other

**Comment by Fargus5** [comment]
XeRicker "The update is being worked on. Since it's a huge update, I'm expecting it to be done within 1-2 weeks."

**Comment by Fargus5** [comment]
[11:45:03] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to CarlTheCreeper v2.5.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:884) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityPlayer.closeInventory(EntityPlayer.java:928) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:451) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.die(EntityHumanNPC.java:212) [citizens.jar:?]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:950) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:577) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:186) [citizens.jar:?]
	at net.minecraft.server.v1_12_R1.EntityMonster.B(EntityMonster.java:68) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityZombie.B(EntityZombie.java:202) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PathfinderGoalZombieAttack.e(SourceFile:28) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:654) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2089) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:505) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityMonster.n(EntityMonster.java:24) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityZombie.n(EntityZombie.java:155) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1938) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:244) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1638) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1608) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1434) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at me.xericker.carlthecreeper.events.OnInventoryCloseEvent.onInventoryClose(OnInventoryCloseEvent.java:16) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	... 34 more

**Comment by xeRicker** [comment]
Update your plugin to the latest version.

**Comment by Fargus5** [comment]
baksovic said: "This internal plugin error of RPGInventory
Caused by: java.lang.NullPointerException
at me.xericker.carlthecreeper.events.OnInventoryCloseEvent.onInventoryClose(OnInventoryCloseEvent.java:16)"

**Comment by Fargus5** [comment]
New issues for RPGPlayerLeveling and BiomeTemp and DisguiseAbilities @xeRicker 

https://hastebin.com/ubofafabir.go

**Comment by Fargus5** [comment]
Leveling and Biome have been fixed, but for leveling there is still this that miss:

`[12:25:16] [Server thread/ERROR]: Could not pass event EntityDeathEvent to RPGPlayerLeveling v3.7.1
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1108) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.EntityZombie.die(EntityZombie.java:429) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:950) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:242) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.mcmonkey.sentinel.SentinelTrait.punch(SentinelTrait.java:748) [sentinel.jar:?]
    at org.mcmonkey.sentinel.SentinelTrait.tryAttack(SentinelTrait.java:1267) [sentinel.jar:?]
    at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1678) [sentinel.jar:?]
    at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1797) [sentinel.jar:?]
    at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430) [citizens.jar:?]
    at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268) [citizens.jar:?]
    at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:158) [citizens.jar:?]
    at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1638) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1025) [citizens.jar:?]
    at net.citizensnpcs.util.NMS.tick(NMS.java:294) [citizens.jar:?]
    at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) [citizens.jar:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
    at me.baks.rpl.manager.VanillaExpManager.setExp(VanillaExpManager.java:13) ~[?:?]
    at me.baks.rpl.listener.EventListener.onDeathEntity(EventListener.java:719) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    ... 28 more`


And DisguiseAbilities miss
