### ISSUE TITLE
[Picmap] java.lang.NullPointerException

### ISSUE THREAD

**Issue by Fargus5** [BalrogGames/herosfaith#18]
[18:36:58] [Server thread/INFO]: Fargus5 issued server command: /picmap create hflogo https://i.imgur.com/dKLz1XQ.png 1 1
[18:36:58] [Server thread/WARN]: A manual (plugin-induced) save has been detected while server is configured to auto-save. This may affect performance.
[18:36:58] [Server thread/INFO]: FactionMobs data saved.
[18:36:58] [Server thread/INFO]: FactionMobs color data saved.
[18:37:04] [Server thread/WARN]: [Picmap] java.lang.NullPointerException
[18:37:04] [Server thread/WARN]: java.lang.NullPointerException
[18:37:04] [Server thread/WARN]:     at com.trainphreak.minecraft.picmap.creator.v1_12_R1.PicmapCreator.run(PicmapCreator.java:329)
[18:37:04] [Server thread/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:37:04] [Server thread/WARN]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:37:04] [Server thread/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[18:37:04] [Server thread/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[18:37:04] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:745)
[18:39:34] [Server thread/INFO]: Fargus5 issued server command: /picmap create hflogo https://i.imgur.com/dKLz1XQ.png 1 1
[18:39:34] [Server thread/INFO]: FactionMobs data saved.
[18:39:34] [Server thread/INFO]: FactionMobs color data saved.
[18:39:39] [Server thread/WARN]: [Picmap] java.lang.NullPointerException
[18:39:39] [Server thread/WARN]: java.lang.NullPointerException
[18:39:39] [Server thread/WARN]:     at com.trainphreak.minecraft.picmap.creator.v1_12_R1.PicmapCreator.run(PicmapCreator.java:329)
[18:39:39] [Server thread/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:39:39] [Server thread/WARN]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:39:39] [Server thread/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[18:39:39] [Server thread/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[18:39:39] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:745)

**Comment by Fargus5** [comment]
https://www.spigotmc.org/conversations/picmap-java-lang-nullpointerexception.273479/
