### ISSUE TITLE
[CarlTheCreeper] An error occurred while loading messages from the language file!

### ISSUE THREAD

**Issue by Erenil** [BalrogGames/herosfaith#19]
[18:54:51] [Server thread/INFO]:  CarlTheCreeper - v2.5.4
[18:54:51] [Server thread/INFO]:  The plugin has been enabled!
[18:54:51] [Server thread/INFO]: ----------------------------------------
[18:54:51] [Server thread/WARN]: [CarlTheCreeper] An error occurred while loading messages from the language file!
[18:54:51] [Server thread/WARN]: [CarlTheCreeper] Disabling the plugin...
[18:54:51] [Server thread/WARN]: java.lang.NullPointerException
[18:54:51] [Server thread/WARN]: 	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324)
[18:54:51] [Server thread/WARN]: 	at me.xericker.carlthecreeper.utils.StringUtils.getColoredString(StringUtils.java:13)
[18:54:51] [Server thread/WARN]: 	at me.xericker.carlthecreeper.other.Language.register(Language.java:45)
[18:54:51] [Server thread/WARN]: 	at me.xericker.carlthecreeper.Main.register(Main.java:73)
[18:54:51] [Server thread/WARN]: 	at me.xericker.carlthecreeper.Main.onEnable(Main.java:33)
[18:54:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:54:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[18:54:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[18:54:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[18:54:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[18:54:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[18:54:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[18:54:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[18:54:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[18:54:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[18:54:51] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:54:51] [Server thread/INFO]: [CarlTheCreeper] Disabling CarlTheCreeper v2.5.4
[18:54:51] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: carlthecreeper
[18:54:51] [Server thread/INFO]: ----------------------------------------
[18:54:51] [Server thread/INFO]:  CarlTheCreeper - v2.5.4
[18:54:51] [Server thread/INFO]:  The plugin has been disabled!
[18:54:51] [Server thread/INFO]: ----------------------------------------
[18:54:51] [Server thread/ERROR]: Error occurred while enabling CarlTheCreeper v2.5.4 (Is it up to date?)
java.lang.NullPointerException: null
	at me.xericker.carlthecreeper.mysql.MySQL.connect(MySQL.java:16) ~[?:?]
	at me.xericker.carlthecreeper.Main.register(Main.java:75) ~[?:?]
	at me.xericker.carlthecreeper.Main.onEnable(Main.java:33) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-bb614f8-595eaaa]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by Erenil** [comment]
Update Carl The Creeper

**Comment by Fargus5** [comment]
OK
