### ISSUE TITLE
Could not pass event InventoryClickEvent to RPGMagic v1.0

### ISSUE THREAD

**Issue by Fargus5** [BalrogGames/herosfaith#21]
[14:30:06] [Server thread/ERROR]: Could not pass event InventoryClickEvent to RPGMagic v1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-bb614f8-595eaaa]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-bb614f8-595eaaa]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NumberFormatException: For input string: "100.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_111]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_111]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_111]
	at me.bumblebeee.rpgmagic.managers.PaperManager.getPwrLvlDist(PaperManager.java:137) ~[?:?]
	at me.bumblebeee.rpgmagic.listeners.inventoryClicks.ShopAlterOther.onInventoryClick(ShopAlterOther.java:149) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor625.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-bb614f8-595eaaa]
	... 15 more

**Comment by Fargus5** [comment]
fixed
