### ISSUE TITLE
General - Be able to get out of the Mimic

### ISSUE THREAD

**Issue by Fargus5** [BalrogGames/herosfaith#3]
Users are still able to get out of the Mimic with spacebar

**Comment by Fargus5** [comment]
`[21:45:55] [Server thread/WARN]: [MimicChest] Task #1851235 for MimicChest v1.0-SNAPSHOT generated an exception
me.bumblebeee_.mimicchest.utils.ParticleEffect$ParticlePacket$VersionIncompatibleException: Your current bukkit version seems to be incompatible with this library
	at me.bumblebeee_.mimicchest.utils.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1414) ~[?:?]
	at me.bumblebeee_.mimicchest.utils.ParticleEffect$ParticlePacket.<init>(ParticleEffect.java:1347) ~[?:?]
	at me.bumblebeee_.mimicchest.utils.ParticleEffect.display(ParticleEffect.java:573) ~[?:?]
	at me.bumblebeee_.mimicchest.utils.Utils$4.run(Utils.java:382) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.Packet63WorldParticles
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_111]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_111]
	at me.bumblebeee_.mimicchest.utils.ReflectionUtils$PackageType.getClass(ReflectionUtils.java:414) ~[?:?]
	at me.bumblebeee_.mimicchest.utils.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1408) ~[?:?]
	... 10 more`

**Comment by Fargus5** [comment]
This should be fixed now. At the next restart, we will try with a test and a debug

**Comment by Fargus5** [comment]
Updated with saved inventory as kill drop
