### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to DisguiseAbilities v2.9.9

### ISSUE THREAD

**Issue by Fargus5** [BalrogGames/herosfaith#7]
`[22:43:58] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to DisguiseAbilities v2.9.9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:92) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:577) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:482) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:609) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1338) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:862) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:242) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.mcmonkey.sentinel.SentinelTrait.punch(SentinelTrait.java:748) [sentinel.jar:?]
	at org.mcmonkey.sentinel.SentinelTrait.tryAttack(SentinelTrait.java:1267) [sentinel.jar:?]
	at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1678) [sentinel.jar:?]
	at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1797) [sentinel.jar:?]
	at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430) [citizens.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268) [citizens.jar:?]
	at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:158) [citizens.jar:?]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1638) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1025) [citizens.jar:?]
	at net.citizensnpcs.util.NMS.tick(NMS.java:294) [citizens.jar:?]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) [citizens.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at me.xericker.disguiseabilities.events.OnEntityDamageEvent.onEntityDamageByEntity(OnEntityDamageEvent.java:54) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor598.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	... 30 more`

**Comment by Fargus5** [comment]
It appear togheter with: https://github.com/BalrogGames/herosfaith/issues/6
