### ISSUE TITLE
Loading map manager 8.5

### ISSUE THREAD

**Issue by Fargus5** [BalrogGames/herosfaith#8]
`[19:07:16] [Server thread/INFO]: [Cartographer] Enabling Cartographer v8.5
[19:07:16] [Server thread/INFO]: [Cartographer] Loading map manager
[19:07:16] [Server thread/ERROR]: Error occurred while enabling Cartographer v8.5 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at io.github.bananapuncher714.cartographer.util.FileUtil.updateConfigFromFile(FileUtil.java:106) ~[?:?]
	at io.github.bananapuncher714.cartographer.CartographerMain.onEnable(CartographerMain.java:104) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

**Comment by Fargus5** [comment]
[09:35:51] [Server thread/INFO]: [Cartographer] Enabling Cartographer v8.8
[09:35:52] [Server thread/INFO]: [Cartographer] Loading map manager
[09:35:52] [Server thread/WARN]: java.lang.NullPointerException
[09:35:52] [Server thread/WARN]: 	at io.github.bananapuncher714.cartographer.util.FileUtil.saveToFile(FileUtil.java:25)
[09:35:52] [Server thread/WARN]: 	at io.github.bananapuncher714.cartographer.CartographerMain.onEnable(CartographerMain.java:122)
[09:35:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:35:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[09:35:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[09:35:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
[09:35:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
[09:35:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
[09:35:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
[09:35:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
[09:35:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[09:35:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
[09:35:52] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[09:35:52] [Server thread/INFO]: [Cartographer] Dumping colors in 'map-colors.yml'
[09:35:52] [Server thread/INFO]: [Cartographer] Loading commands...
[09:35:52] [Server thread/INFO]: [Cartographer] Registering listeners...
[09:35:52] [Server thread/INFO]: [Cartographer] Loading config...
[09:35:52] [Server thread/INFO]: [Cartographer] Loading the fonts...
[09:35:52] [Server thread/INFO]: [Cartographer] Loaded font 'Fancy'!
[09:35:52] [Server thread/INFO]: [Cartographer] Loading the presets...
[09:35:52] [Server thread/INFO]: [Cartographer] Loading the map settings...
[09:35:52] [Server thread/INFO]: [Cartographer] Loading all colors...
[09:35:52] [Server thread/INFO]: [Cartographer] Loaded the colors of preset '1.11.2.yml' successfully!
[09:35:52] [Server thread/INFO]: [Cartographer] Loading all transparent blocks...
[09:35:52] [Server thread/INFO]: [Cartographer] Loaded the transparent blocks of preset '1.11.2.yml' successfully!
[09:35:52] [Server thread/INFO]: [Cartographer] Loading map data...
[09:35:52] [Server thread/WARN]: [Cartographer] Could not save data.yml to plugins/Cartographer/data.yml because data.yml already exists.
[09:35:52] [Server thread/INFO]: [Cartographer] An overlay was not found!!
[09:35:52] [Server thread/WARN]: [Cartographer] Map data not found! Reloading the map!
[09:35:52] [Server thread/INFO]: [Cartographer] Loaded §fDefault Locale(default) successfully!
[09:35:52] [Server thread/INFO]: [Cartographer] The 'radar' module has been loaded!
[09:35:52] [Server thread/INFO]: [Cartographer] The 'kingdoms' module has been loaded!
[09:35:52] [Server thread/INFO]: [Cartographer] The 'quests' module has been loaded!
[09:35:52] [Server thread/INFO]: [Cartographer] The 'display' module has been loaded!
[09:35:52] [Server thread/INFO]: [Cartographer] The 'locale' module has been loaded!
[09:35:52] [Server thread/INFO]: [Cartographer] The 'waypoints' module has been loaded!
[09:35:52] [Server thread/INFO]: [Cartographer] The 'worldguard' module has been loaded!
[09:35:52] [Server thread/INFO]: [Cartographer] The 'citizens' module has been loaded!
[09:35:52] [Server thread/INFO]: [Cartographer] Done loading the config!
[09:35:52] [Server thread/INFO]: [Cartographer] Config loaded successfully!
[09:35:52] [Server thread/INFO]: [Cartographer] Starting map renderer...
